#!/bin/bash
# Auto-generated by setup_daily_refresh.sh
PROJECT_DIR="/Users/mrigaypathak/Desktop/trading app/strategyhub-research"
PYTHON="/Users/mrigaypathak/Desktop/trading app/strategyhub-research/.venv/bin/python"
LOG="/Users/mrigaypathak/Desktop/trading app/strategyhub-research/logs/daily_refresh.log"

cd "$PROJECT_DIR"

echo "[$(date)] Starting daily signal refresh..." >> "$LOG"

# Only run on weekdays
DAY=$(date +%u)  # 1=Mon ... 7=Sun
if [ "$DAY" -ge 6 ]; then
    echo "[$(date)] Weekend — skipping refresh." >> "$LOG"
    exit 0
fi

# Refresh S&P 500 signals
echo "[$(date)] Refreshing S&P 500 signals..." >> "$LOG"
"$PYTHON" scripts/generate_live_signals.py >> "$LOG" 2>&1

# Generate morning trade list (both account sizes)
echo "[$(date)] Generating S&P 500 trade list..." >> "$LOG"
"$PYTHON" scripts/morning_trade_list.py --account 10000 --top 20 >> "$LOG" 2>&1

# Refresh NSE signals
echo "[$(date)] Refreshing NSE signals..." >> "$LOG"
"$PYTHON" scripts/generate_nse_signals.py >> "$LOG" 2>&1

# Generate NSE morning trade list
echo "[$(date)] Generating NSE trade list..." >> "$LOG"
"$PYTHON" scripts/morning_trade_list.py --market nse --account 10000 --top 20 >> "$LOG" 2>&1

# Market sentiment
echo "[$(date)] Running market sentiment..." >> "$LOG"
"$PYTHON" scripts/market_sentiment.py --save >> "$LOG" 2>&1

echo "[$(date)] Daily refresh complete." >> "$LOG"
