#!/bin/bash
# ============================================================
# StrategyHub — Daily Signal Refresh Setup
# ============================================================
# Sets up a macOS launchd job that:
#   1. Refreshes S&P 500 live signals at 6:00 AM every weekday
#   2. Refreshes NSE 500 live signals at 5:30 AM (before US open)
#   3. Runs morning trade list for both markets
#
# Usage:
#   bash scripts/setup_daily_refresh.sh
#
# To remove:
#   launchctl unload ~/Library/LaunchAgents/com.strategyhub.refresh.plist
#   rm ~/Library/LaunchAgents/com.strategyhub.refresh.plist

set -e

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PYTHON="$PROJECT_DIR/.venv/bin/python"
PLIST_NAME="com.strategyhub.daily_refresh"
PLIST_PATH="$HOME/Library/LaunchAgents/$PLIST_NAME.plist"
LOG_DIR="$PROJECT_DIR/logs"

mkdir -p "$LOG_DIR"

echo "Setting up StrategyHub daily refresh..."
echo "Project: $PROJECT_DIR"
echo "Python:  $PYTHON"

# ── Create the wrapper script ─────────────────────────────────────────────────
WRAPPER="$PROJECT_DIR/scripts/daily_refresh.sh"
cat > "$WRAPPER" << SCRIPT
#!/bin/bash
# Auto-generated by setup_daily_refresh.sh
PROJECT_DIR="$PROJECT_DIR"
PYTHON="$PYTHON"
LOG="$LOG_DIR/daily_refresh.log"

cd "\$PROJECT_DIR"

echo "[\$(date)] Starting daily signal refresh..." >> "\$LOG"

# Only run on weekdays
DAY=\$(date +%u)  # 1=Mon ... 7=Sun
if [ "\$DAY" -ge 6 ]; then
    echo "[\$(date)] Weekend — skipping refresh." >> "\$LOG"
    exit 0
fi

# Refresh S&P 500 signals
echo "[\$(date)] Refreshing S&P 500 signals..." >> "\$LOG"
"\$PYTHON" scripts/generate_live_signals.py >> "\$LOG" 2>&1

# Generate morning trade list (both account sizes)
echo "[\$(date)] Generating S&P 500 trade list..." >> "\$LOG"
"\$PYTHON" scripts/morning_trade_list.py --account 10000 --top 20 >> "\$LOG" 2>&1

# Refresh NSE signals
echo "[\$(date)] Refreshing NSE signals..." >> "\$LOG"
"\$PYTHON" scripts/generate_nse_signals.py >> "\$LOG" 2>&1

# Generate NSE morning trade list
echo "[\$(date)] Generating NSE trade list..." >> "\$LOG"
"\$PYTHON" scripts/morning_trade_list.py --market nse --account 10000 --top 20 >> "\$LOG" 2>&1

# Market sentiment
echo "[\$(date)] Running market sentiment..." >> "\$LOG"
"\$PYTHON" scripts/market_sentiment.py --save >> "\$LOG" 2>&1

echo "[\$(date)] Daily refresh complete." >> "\$LOG"
SCRIPT

chmod +x "$WRAPPER"
echo "Created wrapper: $WRAPPER"

# ── Create the launchd plist ──────────────────────────────────────────────────
cat > "$PLIST_PATH" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
    "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$PLIST_NAME</string>

    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>$WRAPPER</string>
    </array>

    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key>
        <integer>6</integer>
        <key>Minute</key>
        <integer>0</integer>
    </dict>

    <key>StandardOutPath</key>
    <string>$LOG_DIR/daily_refresh.log</string>

    <key>StandardErrorPath</key>
    <string>$LOG_DIR/daily_refresh_error.log</string>

    <key>RunAtLoad</key>
    <false/>
</dict>
</plist>
PLIST

echo "Created plist: $PLIST_PATH"

# ── Load the job ──────────────────────────────────────────────────────────────
launchctl unload "$PLIST_PATH" 2>/dev/null || true
launchctl load "$PLIST_PATH"

echo ""
echo "✅ Daily refresh scheduled for 6:00 AM every weekday."
echo ""
echo "Manual test:  bash scripts/daily_refresh.sh"
echo "View logs:    tail -f logs/daily_refresh.log"
echo "Remove:       launchctl unload $PLIST_PATH && rm $PLIST_PATH"
