"""
Live Signals API Routes

Serves the morning trade list and per-strategy current signals
generated by scripts/generate_morning_signals.py.
"""

import json
from pathlib import Path
from fastapi import APIRouter, HTTPException

router = APIRouter(prefix="/signals", tags=["signals"])

RESULTS_DIR   = Path("results") / "live_signals"
TRADE_FILE    = RESULTS_DIR / "morning_trade_list.json"
CURRENT_FILE  = RESULTS_DIR / "current_signals.json"


def _load(path: Path) -> dict:
    if not path.exists():
        return {}
    with open(path) as f:
        return json.load(f)


@router.get("/morning-trade-list")
async def get_morning_trade_list():
    """
    Latest morning trade list.

    Returns the consensus ranked trade list with allocation sizes,
    risk metrics, and sector breakdown. Generated by
    scripts/generate_morning_signals.py.
    """
    data = _load(TRADE_FILE)
    if not data:
        raise HTTPException(
            status_code=404,
            detail="No morning trade list found. Run scripts/generate_morning_signals.py"
        )
    return data


@router.get("/current")
async def get_current_signals():
    """
    Current per-strategy holdings.

    Returns per-strategy signal date, n_holdings, and top holdings.
    """
    data = _load(CURRENT_FILE)
    if not data:
        raise HTTPException(
            status_code=404,
            detail="No current signals found. Run scripts/generate_morning_signals.py"
        )
    return data
