"""
Live Signals API Routes

Serves the morning trade list and per-strategy current signals
generated by scripts/generate_morning_signals.py.
"""

import json
from pathlib import Path
from fastapi import APIRouter, HTTPException

router = APIRouter(prefix="/signals", tags=["signals"])

RESULTS_DIR   = Path("results") / "live_signals"
TRADE_FILE    = RESULTS_DIR / "morning_trade_list.json"
CURRENT_FILE  = RESULTS_DIR / "current_signals.json"
NSE_FILE      = RESULTS_DIR / "nse_signals.json"


def _load(path: Path) -> dict:
    if not path.exists():
        return {}
    with open(path) as f:
        return json.load(f)


@router.get("/morning-trade-list")
async def get_morning_trade_list():
    """
    Latest morning trade list.

    Returns the consensus ranked trade list with allocation sizes,
    risk metrics, and sector breakdown. Generated by
    scripts/generate_morning_signals.py.
    """
    data = _load(TRADE_FILE)
    if not data:
        raise HTTPException(
            status_code=404,
            detail="No morning trade list found. Run scripts/generate_morning_signals.py"
        )
    return data


@router.get("/nse")
async def get_nse_signals():
    """
    Live NSE signals — per-strategy top holdings on NSE 500 universe.
    Also returns a consensus trade list (sum of weights across all strategies).

    Generated by scripts/generate_nse_signals.py
    """
    data = _load(NSE_FILE)
    if not data:
        raise HTTPException(
            status_code=404,
            detail="No NSE signals found. Run scripts/generate_nse_signals.py"
        )

    # Build consensus: sum position weights across all strategies
    from collections import defaultdict
    consensus: dict = defaultdict(float)
    strategy_count: dict = defaultdict(int)
    valid_strategies = 0

    for name, res in data.get("strategies", {}).items():
        if "error" in res or not res.get("holdings"):
            continue
        valid_strategies += 1
        for h in res["holdings"]:
            sym = h["symbol"]
            consensus[sym] += h["weight"]
            strategy_count[sym] += 1

    # Sort by consensus score, take top 20
    ranked = sorted(consensus.items(), key=lambda x: x[1], reverse=True)[:20]
    total_score = sum(v for _, v in ranked)

    trade_list = []
    for rank, (sym, score) in enumerate(ranked, 1):
        alloc_pct = (score / total_score) * 80  # 80% deployed, 20% cash
        trade_list.append({
            "rank": rank,
            "symbol": sym,
            "consensus_score": round(score, 4),
            "n_strategies": strategy_count[sym],
            "allocation_pct": round(alloc_pct, 2),
        })

    return {
        "signal_date":      data.get("signal_date"),
        "generated_at":     data.get("generated_at"),
        "market":           "NSE",
        "n_symbols":        data.get("n_symbols"),
        "n_strategies_ok":  valid_strategies,
        "consensus_trade_list": trade_list,
        "strategies":       data.get("strategies", {}),
    }


@router.get("/current")
async def get_current_signals():
    """
    Current per-strategy holdings.

    Returns per-strategy signal date, n_holdings, and top holdings.
    """
    data = _load(CURRENT_FILE)
    if not data:
        raise HTTPException(
            status_code=404,
            detail="No current signals found. Run scripts/generate_morning_signals.py"
        )
    return data
